//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace FavMovies.HelperClasses
{
	/// <summary>Field Creation Class for entity MovieEntity</summary>
	public partial class MovieFields
	{
		/// <summary>Creates a new MovieEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MovieFieldIndex.Id); }}
		/// <summary>Creates a new MovieEntity.MovieName field instance</summary>
		public static EntityField2 MovieName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MovieFieldIndex.MovieName); }}
	}

	/// <summary>Field Creation Class for entity MovieinfoEntity</summary>
	public partial class MovieinfoFields
	{
		/// <summary>Creates a new MovieinfoEntity.Director field instance</summary>
		public static EntityField2 Director { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MovieinfoFieldIndex.Director); }}
		/// <summary>Creates a new MovieinfoEntity.Genre field instance</summary>
		public static EntityField2 Genre { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MovieinfoFieldIndex.Genre); }}
		/// <summary>Creates a new MovieinfoEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MovieinfoFieldIndex.Id); }}
		/// <summary>Creates a new MovieinfoEntity.MovieId field instance</summary>
		public static EntityField2 MovieId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MovieinfoFieldIndex.MovieId); }}
	}
	

}