//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using FavMovies.FactoryClasses;
using FavMovies.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace FavMovies.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitMovieEntityInfo();
			InitMovieinfoEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits MovieEntity's info objects</summary>
		private void InitMovieEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(MovieFieldIndex), "MovieEntity");
			this.AddElementFieldInfo("MovieEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)MovieFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("MovieEntity", "MovieName", typeof(System.String), false, false, false, false,  (int)MovieFieldIndex.MovieName, 100, 0, 0);
		}

		/// <summary>Inits MovieinfoEntity's info objects</summary>
		private void InitMovieinfoEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(MovieinfoFieldIndex), "MovieinfoEntity");
			this.AddElementFieldInfo("MovieinfoEntity", "Director", typeof(System.String), false, false, false, true,  (int)MovieinfoFieldIndex.Director, 100, 0, 0);
			this.AddElementFieldInfo("MovieinfoEntity", "Genre", typeof(System.String), false, false, false, true,  (int)MovieinfoFieldIndex.Genre, 50, 0, 0);
			this.AddElementFieldInfo("MovieinfoEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)MovieinfoFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("MovieinfoEntity", "MovieId", typeof(System.Int32), false, true, false, false,  (int)MovieinfoFieldIndex.MovieId, 0, 0, 10);
		}
	}
}